name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends libgtk2.0-dev libgtk-3-dev
    - name: Build
      run: |
        cp -r `pwd` ../gtk3
        ./autogen.sh
        make -j`nproc`
        cd ../gtk3
        ./autogen.sh --enable-gtk3
        make -j`nproc`